spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dain
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

